"""empty message

Revision ID: 038f832d6c35
Revises: 
Create Date: 2021-12-07 16:25:30.379702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038f832d6c35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number_of_members', sa.Integer(), nullable=True),
    sa.Column('number_of_posts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_channel_name'), 'channel', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=12), nullable=True),
    sa.Column('subscribed_channels', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_channel_name'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
