"""empty message

Revision ID: 986c33e030f8
Revises: 
Create Date: 2021-12-09 19:39:06.445914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986c33e030f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number_of_members', sa.Integer(), nullable=True),
    sa.Column('number_of_posts', sa.Integer(), nullable=True),
    sa.Column('posts', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_channel_name'), 'channel', ['name'], unique=False)
    op.create_table('course',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number_of_members', sa.Integer(), nullable=True),
    sa.Column('posts', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)
    op.create_table('message',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=100000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=12), nullable=True),
    sa.Column('subscribed_channels', sa.PickleType(), nullable=True),
    sa.Column('subscribed_courses', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_channel_name'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
